name: Aktualizacja EPG

on:
  schedule:
    # Uruchamia się automatycznie co 6 godzin o 02:00, 08:00, 14:00, 20:00
    - cron: '0 12 * * *'
  workflow_dispatch: # Pozwala na ręczne uruchomienie skryptu z panelu GitHuba

jobs:
  update-epg:
    runs-on: ubuntu-latest
    
    # Dodajemy uprawnienia do zapisywania plików w repozytorium
    permissions:
      contents: write

    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v4
        
      - name: Konfiguracja środowiska Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Instalacja wymaganych bibliotek
        run: pip install requests
        
      - name: Pobieranie i generowanie pliku EPG
        run: python update_epg.py
        
      - name: Zapisywanie wyników w repozytorium
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - EPG Bot"
          git add epg_data.json
          # Commit zostanie zrobiony tylko wtedy, gdy dane EPG faktycznie się zmieniły
          git diff --quiet && git diff --staged --quiet || git commit -m "Zaktualizowano plik EPG z epg.ovh"
          git push
